### ISSUE TITLE
[PE-D][Tester C] Format within {}

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#207] opened 2023-03-31 18:40 UTC
![Screenshot 2023-03-31 at 2.53.02 PM.png](https://raw.githubusercontent.com/kohkaixun/ped/main/files/8963e16f-9e6b-4e7f-a636-7b26f2f9e597.png)
Maybe just using | will be clearer instead of &#124;

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kohkaixun/ped#7

**Comment by axmszr** [comment] 2023-04-02 06:37
Duplicate of #201

**Closed by axmszr** 2023-04-02 06:37 UTC
