### ISSUE TITLE
[PE-D][Tester D] Invalid hyperlink in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#224] opened 2023-03-31 20:06 UTC
![Screenshot 2023-03-31 at 7.20.39 PM.png](https://raw.githubusercontent.com/yitong241/ped/main/files/0557ed23-a86f-4de3-84ce-111307b3cd39.png)
The hyperlink for `valid` is not working, clicking on it will not direct the reader anywhere.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: yitong241/ped#7

**Comment by axmszr** [comment] 2023-04-02 06:42
Duplicate of #211

**Closed by axmszr** 2023-04-02 06:42 UTC
