### ISSUE TITLE
[PE-D][Tester D] Formatting Issue in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#185] opened 2023-03-31 17:05 UTC
![Screenshot 2023-03-31 at 2.02.25 PM.png](https://raw.githubusercontent.com/yitong241/ped/main/files/b8610ada-823e-4f27-9977-0070c4b13f85.png)

![Screenshot 2023-03-31 at 2.26.19 PM.png](https://raw.githubusercontent.com/yitong241/ped/main/files/f1beb845-01b8-413d-aae9-279e8ab99531.png)

`&#124` appears as part of command in UG but it is not actually needed.
This makes the content unclear to the reader.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yitong241/ped#1

**Comment by axmszr** [comment] 2023-04-02 06:43
Duplicate of #201

**Closed by axmszr** 2023-04-02 06:43 UTC
