### ISSUE TITLE
[PE-D][Tester E] Unable to execute delete command with sd 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-W17-2/tp#209] opened 2023-03-31 18:50 UTC
![Screenshot 2023-03-31 at 2.55.55 PM.png](https://raw.githubusercontent.com/zuohui48/ped/main/files/6e3665cc-7e04-4a44-a315-1eaa05daad0d.png)

unable to execute the given command in the screen shot even though it is valid. Start date given without end date 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zuohui48/ped#7

**Comment by valerietanhx** [comment] 2023-04-06 04:43
Duplicate of #206, #203

**Closed by valerietanhx** 2023-04-06 04:43 UTC
